### ISSUE TITLE
Default to not include es_staging flag?

### ISSUE THREAD

**Issue by mikeal** [compat-table/node-compat-table#1]
In my experience most people aren't using new features until they are out behind the staging flag so maybe that's a better default.

**Comment by williamkapke** [comment]
But it looks sooo red and discouraging! I might need to change the domain to `node.red` ;)

While I don't know anyone running their production API with the flag- it isn't surprising to see it used with smaller scripts... which people write a lot of. (think Grunt/Gulp size & scope) I hope to encourage people to use the flagged features. If they find bugs and report them- it's a win! That's why the flag exists- right?

So, one of my goals here was to highlight what was available behind flags. I've actually a few dozen people reach out to me and says thanks about that (no complaints though). Unchecking to box doesn't display that it is available behind a flag so I'd prefer not to go that route.

Maybe the yellow ["yes" + flag] on green background doesn't convey the flag requirement enough? I could change it to say "Flag"- would that be better?

How about making the background gold? Full-on stoplight design...
![image](https://cloud.githubusercontent.com/assets/739813/14685439/8552b400-06e9-11e6-9958-b4c388a64d1a.png)

**Comment by mikeal** [comment]
Oh, that's an even better idea ;)

**Comment by jasnell** [comment]
+1 I like the Gold background.

**Comment by williamkapke** [comment]
gold!
via 6bcf1ab3dfe856226eddcd298b892cf80e21ffaf

**Comment by littledan** [comment]
Maybe use --harmony instead of --es-staging? --es-staging includes features that are much less stable. For example, PTC has a number of known bugs in 5.0 which were fixed in 5.1; I believe it is turned on in 5.0 only for --es-staging, not for --harmony. We used the --es-staging flag to get a certain amount of test coverage for ourselves, not to declare that it is ready to use. Further, the PTC feature is still under discussion for possible specification revision at https://github.com/tc39/proposal-ptc-syntax .

**Comment by williamkapke** [comment]
@littledan Very interesting. I'm sure you're correct. I was under the impression `es_staging` was an alias of `harmony`! The [Node.js ES6 page](https://nodejs.org/en/docs/es6/) says:

> - Staged features, which are almost-completed features that are not considered stable by the V8 team, require a runtime flag: --es_staging (or its synonym, --harmony).

I ran the tests with the --harmony flag locally on a branch & pushed the results. Check out the compare:
https://github.com/williamkapke/node-compat-table/compare/gh-pages...williamkapke:harmony

v12 shows significant changes... but nothing in Node v4,v5. Then on the nightly there is only a change with PTC. Is that what is expected? 

I think the ES6 page might needs some clarification. I'll mention it over there.

**Comment by littledan** [comment]
I don't know a lot about what was happening in v12 days (maybe it's fine to use --es-staging there; I have no opinion), but recently, we have only rarely made a distinction between --es-staging and --harmony. Critically, though, if you go into about:flags in Chrome and flip on "Experimental JavaScript features", you'll turn on only --harmony and not the features that are only in --es-staging but not --harmony. For the main Kangax tables, the "flagged" thing indicates that about:flags flag, namely --harmony. I like how your patch makes parity with this.

**Comment by williamkapke** [comment]
@littledan ok, I am now running the tests with the `--es_staging` _**AND**_ `--harmony` flags. So, now there are 3 results files for each version of Node. The `--es_staging` result files are just being updated in the repo for reference if someone is ever interested.

The webpage now uses and references the `--harmony` flag.

**Comment by taxilian** [comment]
as an FYI, I found this page while trying to find information on what a yellow "yes" means; I still am not sure I understand

**Comment by littledan** [comment]
Yellow means that it works with --harmony, a mode which is not guaranteed to be as fast or correct as without that flag. I'd recommend not using that flag.
