### ISSUE TITLE
Better way to denote failures due to strict mode

### ISSUE THREAD

**Issue by daprahamian** [compat-table/node-compat-table#15]
Currently, items like `let`, `const` and `Class` display Error for Node v4.4.3. This is due to the following error message:

[  "functions›class›class statement": "Block-scoped declarations (let, const, function, class) not yet supported outside strict mode",](https://github.com/williamkapke/node-compat-table/blob/gh-pages/results/4.4.3.json#L180)

This is deceptive, since it implies that there is no support for these features.

Is there a better way to denote this?

**Comment by dougwilson** [comment]
@williamkapke, since there is logic to retry tests under `use strict`, this would seem like a bug to me, right? I remember seeing when I was converting from Promise to callback, there was logic to only retry if the test failed without an error message, and I preserved that behavior. I believe if it were changes to retry under any non-successful outcome, it would flip all these tests to true. Thoughts?

**Comment by daprahamian** [comment]
Looking at it closer, both `let` and `const` have separate rows for strict mode that denote a success. It doesn't appear that clases have this though.

**Comment by dougwilson** [comment]
@daprahamian, the tests run in this project are as-is from the https://github.com/kangax/compat-table project from which this is forked. That project happens to test those in strict & not, but it doesn't look like they do that for Classes. Certainly if the parent project adds those tests, this one will pull them in.

**Comment by williamkapke** [comment]
I dug into this a bit more. The goal of this project has been to illustrate "what **_is possible_** on each version of node" (which is why it defaults to showing the `--harmony` flagged features). Part of that is to test with & without strict mode. ([test262](https://github.com/tc39/test262/blob/master/INTERPRETING.md#strict-mode) also wants things tested with both for it's purposes).

@daprahamian, it turns out you noticed a pretty big bug. The way the code has been written, it only runs the strict mode tests if `result===false`. That's not how it was supposed to be :( It should be trying strict mode if `!result || typeof result==='string'` (always try unless it was successful).

I fixed the code and re-ran the tests. About 10% more tests are passing now in v4 and v5. Node v6 did not have any results change.

Thanks for helping uncover this!

**Comment by daprahamian** [comment]
@williamkapke Glad to help! thank you for fixing this!
