### ISSUE TITLE
couldn't find: ./results/4.4.0--harmony.json

### ISSUE THREAD

**Issue by ghost** [compat-table/node-compat-table#21]
Cloned your repo and ran 'node build.js' but wanted to find out the feature set for 4.4.0. Results in:
couldn't find: ./results/4.4.0--harmony.json

It appears the repo is missing that file.

**Comment by williamkapke** [comment]
4.4.0 was just before we found out that we should be using the `--harmony` flag instead of `--es_staging`. Once versions are cycled out of the `.versions` file, they no longer are tested and displayed on the website.

`build.js` creates the webpage based off the `.versions` file so I'm guessing you put 4.4.0 in the versions file which caused the error...?

While on node v4.4.0, run `node --harmony test.js` and that will generate the results file it is complaining about. Then run `node build.js` again.

LMK, if you hit any more snags (or if I forgot something!).

**Comment by ghost** [comment]
Thanks for the update. JSYK, I had to switch back to using a higher version of node before running `node build.js` due to the fact I was getting 

```
node build.js
/git/node-compat-table/build.js:63
function $get (obj, path, ...more) {
                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by williamkapke** [comment]
Ah yes. The build portion is always run on the latest version of node :D 

It sounds like you got it working otherwise. Thanks for the info- I'm sure this will help someone else!
