### ISSUE TITLE
Add id's to everything

### ISSUE THREAD

**Issue by jimmywarting** [compat-table/node-compat-table#27]
Would be nice to be able to link to a specific feature on your website eg like this:

http://node.green/#String_prototype_repeat

**Comment by williamkapke** [comment]
Are you up for doing a PR for this?

I think it would just need a change here:
https://github.com/williamkapke/node-compat-table/blob/gh-pages/index.jade#L53

... hmmm... it _might_ also need css adjustments if you add `<a>` elements.

**Comment by williamkapke** [comment]
Done!

**Comment by jimmywarting** [comment]
Thanks!, one thing that would be nice doe is some sort of styling on the one that is currently targeted 

Simple demo: http://webdesignernotebook.com/examples/target.html
docs: http://webdesignernotebook.com/css/the-css3-target-pseudo-class-and-css-animations/

**Comment by williamkapke** [comment]
I started down that path but didn't have time. It is usually simple enough- but because there is the fixed header, I put `div.hash` elements with the ids that are `position:absolute; margin-top:-46px;` to compensate. This can certainly be done a different way to make it happen. I just ran out of time.

PR? :)
