### ISSUE TITLE
8.0

### ISSUE THREAD

**Issue by kachkaev** [compat-table/node-compat-table#40]
Hi William! Can you please consider updating the table so that it includes v8.0? Cheers!

**Comment by williamkapke** [comment]
It's there!

... buuuuut because of the way I made it group versions with identical results, it is hidden under the nightly version 👎  #SMH hah

![image](https://cloud.githubusercontent.com/assets/739813/26833132/71dd08a8-4a86-11e7-88ea-f7e7974ae225.png)

I think I need to add an `if (!nightly)` somewhere/somehow 🤔

**Comment by williamkapke** [comment]
Ok. Fixed. Thanks for the heads up!
